FROM gradle:jdk11 AS builder

WORKDIR /home/gradle/
COPY . .

RUN gradle :profiling:build

FROM amazoncorretto:11

COPY --from=builder /home/gradle/profiling/build/libs/* /app/

WORKDIR /app/

CMD [ "sh", "-c", "java -jar profiling-1.0.jar ${JAVA_PARAMS}" ]
